#!/usr/bin/env sh
export APPNAME_PATH=`pwd`

export NODE_PATH=\
$NODE_PATH\
:$APPNAME_PATH\
:$APPNAME_PATH/deps/redis-node\
:$APPNAME_PATH/deps/underscore\
:$APPNAME_PATH/deps/taglib\
:$APPNAME_PATH/deps/nerve

node "$@"
