#!/usr/bin/env sh
export MINESTRONE_PATH=`pwd`

export NODE_PATH=\
$NODE_PATH\
:$MINESTRONE_PATH\
:$MINESTRONE_PATH/deps/redis-node\
:$MINESTRONE_PATH/deps/underscore\
:$MINESTRONE_PATH/deps/taglib\
:$MINESTRONE_PATH/deps/jssha\
:$MINESTRONE_PATH/deps/nerve

node "$@"
