#!/usr/bin/python

import hashlib, sys, os, redis, glob, subprocess

r = redis.Redis()

# so that run works
os.chdir('../')
for fn in glob.iglob(os.path.join(sys.argv[1], '*.mp3')):
    path = os.path.join(sys.argv[1], fn)
    path.replace(' ', '\\ ')
    subprocess.call(['./run', 'tools/insmeta.js', path, hashlib.md5(path).hexdigest()] )
